image: node:10

# services:
#   - mysql:latest
#   - redis:latest
#   - postgres:latest

stages:
  - test
  - build
  - deploy_review
  - deploy_staging
  - deploy_production

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - node_modules/

variables:
  STAGING_DOMAIN: tantora-staging.surge.sh
  REVIEW_DOMAIN: tantora-$CI_ENVIRONMENT_SLUG.surge.sh

test:
  stage: test
  only:
    - master
    - development
    - merge_requests
  script:
    - yarn
    - yarn run format
    - yarn run check

build_stage:
  stage: build
  only:
    - master
    - development
    - merge_requests
  before_script:
    - yarn
  script: yarn run build
  artifacts:
    paths:
      - build/
  variables:
    REACT_APP_BACKEND_URL: http://18.163.6.250/api/graphql
    REACT_APP_CHAT_URL: http://18.163.6.250/api-chat

.deploy_base: &deploy
  script:
    - npm install --global surge
    - surge --project ./build --domain $DOMAIN

deploy_review:
  <<: *deploy
  stage: deploy_review
  only:
    - merge_requests
  environment:
    name: review/$CI_COMMIT_REF_NAME
    url: https://tantora-$CI_ENVIRONMENT_SLUG.surge.sh
    on_stop: stop_review
  variables:
    DOMAIN: $REVIEW_DOMAIN
  dependencies:
    - build_stage

stop_review:
  stage: deploy_review
  only:
    - merge_requests
  variables:
    GIT_STRATEGY: none
  script:
    - npm install --global surge
    - surge teardown $REVIEW_DOMAIN
  when: manual
  environment:
    name: review/$CI_COMMIT_REF_NAME
    action: stop

deploy_staging:
  <<: *deploy
  stage: deploy_staging
  environment:
    name: staging
    url: http://$STAGING_DOMAIN
  only:
    - development
  variables:
    DOMAIN: $STAGING_DOMAIN
  dependencies:
    - build_stage

deploy_production:
  stage: deploy_production
  only:
    - master
  before_script:
    - mkdir -p ~/.ssh
    - ssh-keyscan -t rsa $EC2_HOST >> ~/.ssh/known_hosts
    - chmod 400 $PRIVATE_KEY
  script:
    - >
      ssh -i $PRIVATE_KEY ec2-user@$EC2_HOST "
      cd ~/tantora_front &&
      echo hello > hello.txt &&
      cat hello.txt"
  dependencies:
    - build_stage